"""initial setup

Revision ID: 43e41817990d
Revises: 
Create Date: 2024-01-16 10:41:47.563423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e41817990d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_courses_course_code', table_name='courses')
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=False)
    op.drop_index('ix_courses_course_name', table_name='courses')
    op.create_index(op.f('ix_courses_course_name'), 'courses', ['course_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_course_name'), table_name='courses')
    op.create_index('ix_courses_course_name', 'courses', ['course_name'], unique=True)
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.create_index('ix_courses_course_code', 'courses', ['course_code'], unique=True)
    # ### end Alembic commands ###
