"""initial setup

Revision ID: 5790ea51a900
Revises: 4b8af9f625f6
Create Date: 2024-02-29 23:51:44.664113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5790ea51a900'
down_revision: Union[str, None] = '4b8af9f625f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_path',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('engineering_discipline', sa.String(), nullable=True),
    sa.Column('course_order', sa.Integer(), nullable=True),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['courses.course_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sample_path_course_order'), 'sample_path', ['course_order'], unique=False)
    op.create_index(op.f('ix_sample_path_engineering_discipline'), 'sample_path', ['engineering_discipline'], unique=False)
    op.alter_column('options', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('options', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_sample_path_engineering_discipline'), table_name='sample_path')
    op.drop_index(op.f('ix_sample_path_course_order'), table_name='sample_path')
    op.drop_table('sample_path')
    # ### end Alembic commands ###
