"""add major and option columns

Revision ID: 74c03bfb3db7
Revises: 7f988ce646e9
Create Date: 2024-01-25 00:11:17.418255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c03bfb3db7'
down_revision: Union[str, None] = '7f988ce646e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('engineering_discipline', sa.Column('course_codes', sa.String(), nullable=True))
    op.add_column('engineering_discipline', sa.Column('number_of_courses', sa.Integer(), nullable=True))
    op.add_column('engineering_discipline', sa.Column('credits_required', sa.Float(), nullable=True))
    op.add_column('engineering_discipline', sa.Column('additional_requirements', sa.String(), nullable=True))
    op.add_column('engineering_discipline', sa.Column('link', sa.String(), nullable=True))
    op.add_column('engineering_discipline', sa.Column('year', sa.String(), nullable=True))
    op.add_column('options', sa.Column('course_codes', sa.String(), nullable=True))
    op.add_column('options', sa.Column('number_of_courses', sa.Integer(), nullable=True))
    op.add_column('options', sa.Column('additional_requirements', sa.String(), nullable=True))
    op.add_column('options', sa.Column('link', sa.String(), nullable=True))
    op.add_column('options', sa.Column('year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('options', 'year')
    op.drop_column('options', 'link')
    op.drop_column('options', 'additional_requirements')
    op.drop_column('options', 'number_of_courses')
    op.drop_column('options', 'course_codes')
    op.drop_column('engineering_discipline', 'year')
    op.drop_column('engineering_discipline', 'link')
    op.drop_column('engineering_discipline', 'additional_requirements')
    op.drop_column('engineering_discipline', 'credits_required')
    op.drop_column('engineering_discipline', 'number_of_courses')
    op.drop_column('engineering_discipline', 'course_codes')
    # ### end Alembic commands ###
