"""fix requirements tables

Revision ID: 7f988ce646e9
Revises: b6190cf4ef5b
Create Date: 2024-01-22 14:09:05.620003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f988ce646e9'
down_revision: Union[str, None] = 'b6190cf4ef5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antirequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('courses', sa.String(), nullable=True),
    sa.Column('extra_info', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_antirequisites_courses'), 'antirequisites', ['courses'], unique=False)
    op.create_table('prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('logic', sa.String(), nullable=True),
    sa.Column('courses', sa.String(), nullable=True),
    sa.Column('min_level', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prerequisites_courses'), 'prerequisites', ['courses'], unique=False)
    op.create_index(op.f('ix_prerequisites_logic'), 'prerequisites', ['logic'], unique=False)
    op.create_index(op.f('ix_prerequisites_min_level'), 'prerequisites', ['min_level'], unique=False)
    op.drop_table('course_prerequisites')
    op.drop_table('course_antirequisites')
    op.drop_table('course_corequisites')
    op.add_column('courses', sa.Column('requirements_description', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('prerequisites', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('antirequisites', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('corequisites', sa.String(), nullable=True))
    op.create_index(op.f('ix_courses_antirequisites'), 'courses', ['antirequisites'], unique=False)
    op.create_index(op.f('ix_courses_corequisites'), 'courses', ['corequisites'], unique=False)
    op.create_index(op.f('ix_courses_prerequisites'), 'courses', ['prerequisites'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_prerequisites'), table_name='courses')
    op.drop_index(op.f('ix_courses_corequisites'), table_name='courses')
    op.drop_index(op.f('ix_courses_antirequisites'), table_name='courses')
    op.drop_column('courses', 'corequisites')
    op.drop_column('courses', 'antirequisites')
    op.drop_column('courses', 'prerequisites')
    op.drop_column('courses', 'requirements_description')
    op.create_table('course_corequisites',
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('corequisite_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['corequisite_id'], ['courses.id'], name='course_corequisites_corequisite_id_fkey'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='course_corequisites_course_id_fkey')
    )
    op.create_table('course_antirequisites',
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('antirequisite_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['antirequisite_id'], ['courses.id'], name='course_antirequisites_antirequisite_id_fkey'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='course_antirequisites_course_id_fkey')
    )
    op.create_table('course_prerequisites',
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prerequisite_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='course_prerequisites_course_id_fkey'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['courses.id'], name='course_prerequisites_prerequisite_id_fkey')
    )
    op.drop_index(op.f('ix_prerequisites_min_level'), table_name='prerequisites')
    op.drop_index(op.f('ix_prerequisites_logic'), table_name='prerequisites')
    op.drop_index(op.f('ix_prerequisites_courses'), table_name='prerequisites')
    op.drop_table('prerequisites')
    op.drop_index(op.f('ix_antirequisites_courses'), table_name='antirequisites')
    op.drop_table('antirequisites')
    # ### end Alembic commands ###
