"""initial setup

Revision ID: b6190cf4ef5b
Revises: 
Create Date: 2024-01-19 22:57:53.102773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6190cf4ef5b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(), nullable=True),
    sa.Column('course_name', sa.String(), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    op.create_index(op.f('ix_courses_course_name'), 'courses', ['course_name'], unique=False)
    op.create_index(op.f('ix_courses_credit'), 'courses', ['credit'], unique=False)
    op.create_index(op.f('ix_courses_description'), 'courses', ['description'], unique=False)
    op.create_index(op.f('ix_courses_location'), 'courses', ['location'], unique=True)
    op.create_table('engineering_discipline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipline_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineering_discipline_discipline_name'), 'engineering_discipline', ['discipline_name'], unique=True)
    op.create_table('options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('option_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_option_name'), 'options', ['option_name'], unique=False)
    op.create_table('course_antirequisites',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('antirequisite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['antirequisite_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], )
    )
    op.create_table('course_corequisites',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('corequisite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corequisite_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], )
    )
    op.create_table('course_prerequisites',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['courses.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_prerequisites')
    op.drop_table('course_corequisites')
    op.drop_table('course_antirequisites')
    op.drop_index(op.f('ix_options_option_name'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_engineering_discipline_discipline_name'), table_name='engineering_discipline')
    op.drop_table('engineering_discipline')
    op.drop_index(op.f('ix_courses_location'), table_name='courses')
    op.drop_index(op.f('ix_courses_description'), table_name='courses')
    op.drop_index(op.f('ix_courses_credit'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
