"""initial setup

Revision ID: d431f6190a36
Revises: 5a5952cc0d04
Create Date: 2024-01-15 22:23:19.531250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd431f6190a36'
down_revision: Union[str, None] = '5a5952cc0d04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_corequisites',
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('corequisite_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['corequisite_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], )
    )
    op.add_column('courses', sa.Column('course_code', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('course_name', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('credit', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('description', sa.String(), nullable=True))
    op.add_column('courses', sa.Column('location', sa.String(), nullable=True))
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    op.create_index(op.f('ix_courses_course_name'), 'courses', ['course_name'], unique=True)
    op.create_index(op.f('ix_courses_credit'), 'courses', ['credit'], unique=False)
    op.create_index(op.f('ix_courses_description'), 'courses', ['description'], unique=False)
    op.create_index(op.f('ix_courses_location'), 'courses', ['location'], unique=True)
    op.add_column('engineering_discipline', sa.Column('discipline_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_engineering_discipline_discipline_name'), 'engineering_discipline', ['discipline_name'], unique=True)
    op.add_column('options', sa.Column('option_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_options_option_name'), 'options', ['option_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_options_option_name'), table_name='options')
    op.drop_column('options', 'option_name')
    op.drop_index(op.f('ix_engineering_discipline_discipline_name'), table_name='engineering_discipline')
    op.drop_column('engineering_discipline', 'discipline_name')
    op.drop_index(op.f('ix_courses_location'), table_name='courses')
    op.drop_index(op.f('ix_courses_description'), table_name='courses')
    op.drop_index(op.f('ix_courses_credit'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.drop_column('courses', 'location')
    op.drop_column('courses', 'description')
    op.drop_column('courses', 'credit')
    op.drop_column('courses', 'course_name')
    op.drop_column('courses', 'course_code')
    op.drop_table('course_corequisites')
    # ### end Alembic commands ###
