"""make discipline name non unique

Revision ID: ec9ecc731b7b
Revises: 74c03bfb3db7
Create Date: 2024-01-25 01:00:41.717691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec9ecc731b7b'
down_revision: Union[str, None] = '74c03bfb3db7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_engineering_discipline_discipline_name', table_name='engineering_discipline')
    op.create_index(op.f('ix_engineering_discipline_discipline_name'), 'engineering_discipline', ['discipline_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_engineering_discipline_discipline_name'), table_name='engineering_discipline')
    op.create_index('ix_engineering_discipline_discipline_name', 'engineering_discipline', ['discipline_name'], unique=True)
    # ### end Alembic commands ###
